version: "3.6"
services:  
  grafana:
    image: grafana/grafana:7.3.5
    hostname: grafana
    environment:
      - "GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/"
      - GF_SERVER_HTTP_PORT=3000
    ports:
      - "3000:3000"