version: "3.6"
services:    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    hostname: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=true
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2      
    hostname: elasticsearch
    environment:
      - node.name=elasticsearch-01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m -Des.index.max_number_of_shards=128"
      - TZ=America/Sao_Paulo 
    volumes:
      - ./storage/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300